version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: BarceloNA26.
      MYSQL_DATABASE: sigva_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: BarceloNA26.
    ports:
      - "8080:80"

  web:
    build: 
      context: .
      dockerfile: Dockerfile  # 👉 Usa un Dockerfile personalizado
    container_name: apache_container
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html  # 👉 Monta tu código PHP
    depends_on:
      - mysql

volumes:
  mysql_data:


